name: derek matthew duke
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1139
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: ignore my antlers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0A0000'
    - '#21503B'
    - '#B52A32'
    - '#CE984B'
    - '#FBEADB'
  brandStrength: 0.2681707816664129
  lightness: 0.1290335091762245
  saturation: 0.4543923197779804
  rhythmicContrast: 0.7138677455950528
purpose: []
