collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4543923197779804
  brandStrength: 0.2681707816664129
  rhythmicContrast: 0.7138677455950528
  brandColors:
    - '#0A0000'
    - '#21503B'
    - '#B52A32'
    - '#CE984B'
    - '#FBEADB'
  lightness: 0.1290335091762245
typography_spectrum: 0.1875
description: ignore my antlers
layout_spectrum: 0.7626680778339505
name: derek matthew duke
